// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: pkg/gamenodepb/gamenodepb.proto

package gamenodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Backend_Type int32

const (
	Backend_FILE Backend_Type = 0
	Backend_JOY  Backend_Type = 1
	Backend_KBD  Backend_Type = 2
	Backend_SND  Backend_Type = 3
)

// Enum value maps for Backend_Type.
var (
	Backend_Type_name = map[int32]string{
		0: "FILE",
		1: "JOY",
		2: "KBD",
		3: "SND",
	}
	Backend_Type_value = map[string]int32{
		"FILE": 0,
		"JOY":  1,
		"KBD":  2,
		"SND":  3,
	}
)

func (x Backend_Type) Enum() *Backend_Type {
	p := new(Backend_Type)
	*p = x
	return p
}

func (x Backend_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Backend_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_gamenodepb_gamenodepb_proto_enumTypes[0].Descriptor()
}

func (Backend_Type) Type() protoreflect.EnumType {
	return &file_pkg_gamenodepb_gamenodepb_proto_enumTypes[0]
}

func (x Backend_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Backend_Type.Descriptor instead.
func (Backend_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{0, 0}
}

type Backend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Backend) Reset() {
	*x = Backend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type FileEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Obj:
	//	*FileEvent_Line_
	Obj isFileEvent_Obj `protobuf_oneof:"Obj"`
}

func (x *FileEvent) Reset() {
	*x = FileEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent) ProtoMessage() {}

func (x *FileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent.ProtoReflect.Descriptor instead.
func (*FileEvent) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{2}
}

func (m *FileEvent) GetObj() isFileEvent_Obj {
	if m != nil {
		return m.Obj
	}
	return nil
}

func (x *FileEvent) GetLine() *FileEvent_Line {
	if x, ok := x.GetObj().(*FileEvent_Line_); ok {
		return x.Line
	}
	return nil
}

type isFileEvent_Obj interface {
	isFileEvent_Obj()
}

type FileEvent_Line_ struct {
	Line *FileEvent_Line `protobuf:"bytes,1,opt,name=line,proto3,oneof"`
}

func (*FileEvent_Line_) isFileEvent_Obj() {}

type JoyEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Obj:
	//	*JoyEvent_Device_
	//	*JoyEvent_Mfd
	//	*JoyEvent_Button_
	//	*JoyEvent_Hud_
	//	*JoyEvent_Led_
	Obj isJoyEvent_Obj `protobuf_oneof:"Obj"`
}

func (x *JoyEvent) Reset() {
	*x = JoyEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent) ProtoMessage() {}

func (x *JoyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent.ProtoReflect.Descriptor instead.
func (*JoyEvent) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{3}
}

func (m *JoyEvent) GetObj() isJoyEvent_Obj {
	if m != nil {
		return m.Obj
	}
	return nil
}

func (x *JoyEvent) GetDevice() *JoyEvent_Device {
	if x, ok := x.GetObj().(*JoyEvent_Device_); ok {
		return x.Device
	}
	return nil
}

func (x *JoyEvent) GetMfd() *JoyEvent_MFD {
	if x, ok := x.GetObj().(*JoyEvent_Mfd); ok {
		return x.Mfd
	}
	return nil
}

func (x *JoyEvent) GetButton() *JoyEvent_Button {
	if x, ok := x.GetObj().(*JoyEvent_Button_); ok {
		return x.Button
	}
	return nil
}

func (x *JoyEvent) GetHud() *JoyEvent_Hud {
	if x, ok := x.GetObj().(*JoyEvent_Hud_); ok {
		return x.Hud
	}
	return nil
}

func (x *JoyEvent) GetLed() *JoyEvent_Led {
	if x, ok := x.GetObj().(*JoyEvent_Led_); ok {
		return x.Led
	}
	return nil
}

type isJoyEvent_Obj interface {
	isJoyEvent_Obj()
}

type JoyEvent_Device_ struct {
	Device *JoyEvent_Device `protobuf:"bytes,10,opt,name=device,proto3,oneof"`
}

type JoyEvent_Mfd struct {
	Mfd *JoyEvent_MFD `protobuf:"bytes,11,opt,name=mfd,proto3,oneof"`
}

type JoyEvent_Button_ struct {
	Button *JoyEvent_Button `protobuf:"bytes,12,opt,name=button,proto3,oneof"`
}

type JoyEvent_Hud_ struct {
	Hud *JoyEvent_Hud `protobuf:"bytes,13,opt,name=hud,proto3,oneof"`
}

type JoyEvent_Led_ struct {
	Led *JoyEvent_Led `protobuf:"bytes,14,opt,name=led,proto3,oneof"`
}

func (*JoyEvent_Device_) isJoyEvent_Obj() {}

func (*JoyEvent_Mfd) isJoyEvent_Obj() {}

func (*JoyEvent_Button_) isJoyEvent_Obj() {}

func (*JoyEvent_Hud_) isJoyEvent_Obj() {}

func (*JoyEvent_Led_) isJoyEvent_Obj() {}

type KbdEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Obj:
	//	*KbdEvent_Key_
	//	*KbdEvent_Led_
	Obj isKbdEvent_Obj `protobuf_oneof:"Obj"`
}

func (x *KbdEvent) Reset() {
	*x = KbdEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KbdEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KbdEvent) ProtoMessage() {}

func (x *KbdEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KbdEvent.ProtoReflect.Descriptor instead.
func (*KbdEvent) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{4}
}

func (m *KbdEvent) GetObj() isKbdEvent_Obj {
	if m != nil {
		return m.Obj
	}
	return nil
}

func (x *KbdEvent) GetKey() *KbdEvent_Key {
	if x, ok := x.GetObj().(*KbdEvent_Key_); ok {
		return x.Key
	}
	return nil
}

func (x *KbdEvent) GetLed() *KbdEvent_Led {
	if x, ok := x.GetObj().(*KbdEvent_Led_); ok {
		return x.Led
	}
	return nil
}

type isKbdEvent_Obj interface {
	isKbdEvent_Obj()
}

type KbdEvent_Key_ struct {
	Key *KbdEvent_Key `protobuf:"bytes,10,opt,name=key,proto3,oneof"`
}

type KbdEvent_Led_ struct {
	Led *KbdEvent_Led `protobuf:"bytes,11,opt,name=led,proto3,oneof"`
}

func (*KbdEvent_Key_) isKbdEvent_Obj() {}

func (*KbdEvent_Led_) isKbdEvent_Obj() {}

type SndEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Obj:
	//	*SndEvent_Track_
	Obj isSndEvent_Obj `protobuf_oneof:"Obj"`
}

func (x *SndEvent) Reset() {
	*x = SndEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SndEvent) ProtoMessage() {}

func (x *SndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SndEvent.ProtoReflect.Descriptor instead.
func (*SndEvent) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{5}
}

func (m *SndEvent) GetObj() isSndEvent_Obj {
	if m != nil {
		return m.Obj
	}
	return nil
}

func (x *SndEvent) GetTrack() *SndEvent_Track {
	if x, ok := x.GetObj().(*SndEvent_Track_); ok {
		return x.Track
	}
	return nil
}

type isSndEvent_Obj interface {
	isSndEvent_Obj()
}

type SndEvent_Track_ struct {
	Track *SndEvent_Track `protobuf:"bytes,10,opt,name=track,proto3,oneof"`
}

func (*SndEvent_Track_) isSndEvent_Obj() {}

type FileMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Msg:
	//	*FileMsg_Event
	//	*FileMsg_Error
	Msg   isFileMsg_Msg `protobuf_oneof:"Msg"`
	SeqNo int32         `protobuf:"varint,99,opt,name=seqNo,proto3" json:"seqNo,omitempty"`
}

func (x *FileMsg) Reset() {
	*x = FileMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMsg) ProtoMessage() {}

func (x *FileMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMsg.ProtoReflect.Descriptor instead.
func (*FileMsg) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{6}
}

func (x *FileMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *FileMsg) GetMsg() isFileMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *FileMsg) GetEvent() *FileEvent {
	if x, ok := x.GetMsg().(*FileMsg_Event); ok {
		return x.Event
	}
	return nil
}

func (x *FileMsg) GetError() *Error {
	if x, ok := x.GetMsg().(*FileMsg_Error); ok {
		return x.Error
	}
	return nil
}

func (x *FileMsg) GetSeqNo() int32 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

type isFileMsg_Msg interface {
	isFileMsg_Msg()
}

type FileMsg_Event struct {
	Event *FileEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type FileMsg_Error struct {
	Error *Error `protobuf:"bytes,9,opt,name=error,proto3,oneof"`
}

func (*FileMsg_Event) isFileMsg_Msg() {}

func (*FileMsg_Error) isFileMsg_Msg() {}

type JoyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Msg:
	//	*JoyMsg_Event
	//	*JoyMsg_Error
	Msg   isJoyMsg_Msg `protobuf_oneof:"Msg"`
	SeqNo int32        `protobuf:"varint,99,opt,name=seqNo,proto3" json:"seqNo,omitempty"`
}

func (x *JoyMsg) Reset() {
	*x = JoyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyMsg) ProtoMessage() {}

func (x *JoyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyMsg.ProtoReflect.Descriptor instead.
func (*JoyMsg) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{7}
}

func (x *JoyMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *JoyMsg) GetMsg() isJoyMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *JoyMsg) GetEvent() *JoyEvent {
	if x, ok := x.GetMsg().(*JoyMsg_Event); ok {
		return x.Event
	}
	return nil
}

func (x *JoyMsg) GetError() *Error {
	if x, ok := x.GetMsg().(*JoyMsg_Error); ok {
		return x.Error
	}
	return nil
}

func (x *JoyMsg) GetSeqNo() int32 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

type isJoyMsg_Msg interface {
	isJoyMsg_Msg()
}

type JoyMsg_Event struct {
	Event *JoyEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type JoyMsg_Error struct {
	Error *Error `protobuf:"bytes,9,opt,name=error,proto3,oneof"`
}

func (*JoyMsg_Event) isJoyMsg_Msg() {}

func (*JoyMsg_Error) isJoyMsg_Msg() {}

type KbdMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Msg:
	//	*KbdMsg_Event
	//	*KbdMsg_Error
	Msg   isKbdMsg_Msg `protobuf_oneof:"Msg"`
	SeqNo int32        `protobuf:"varint,99,opt,name=seqNo,proto3" json:"seqNo,omitempty"`
}

func (x *KbdMsg) Reset() {
	*x = KbdMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KbdMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KbdMsg) ProtoMessage() {}

func (x *KbdMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KbdMsg.ProtoReflect.Descriptor instead.
func (*KbdMsg) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{8}
}

func (x *KbdMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *KbdMsg) GetMsg() isKbdMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *KbdMsg) GetEvent() *KbdEvent {
	if x, ok := x.GetMsg().(*KbdMsg_Event); ok {
		return x.Event
	}
	return nil
}

func (x *KbdMsg) GetError() *Error {
	if x, ok := x.GetMsg().(*KbdMsg_Error); ok {
		return x.Error
	}
	return nil
}

func (x *KbdMsg) GetSeqNo() int32 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

type isKbdMsg_Msg interface {
	isKbdMsg_Msg()
}

type KbdMsg_Event struct {
	Event *KbdEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type KbdMsg_Error struct {
	Error *Error `protobuf:"bytes,9,opt,name=error,proto3,oneof"`
}

func (*KbdMsg_Event) isKbdMsg_Msg() {}

func (*KbdMsg_Error) isKbdMsg_Msg() {}

type SndMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Msg:
	//	*SndMsg_Event
	//	*SndMsg_Error
	Msg   isSndMsg_Msg `protobuf_oneof:"Msg"`
	SeqNo int32        `protobuf:"varint,99,opt,name=seqNo,proto3" json:"seqNo,omitempty"`
}

func (x *SndMsg) Reset() {
	*x = SndMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SndMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SndMsg) ProtoMessage() {}

func (x *SndMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SndMsg.ProtoReflect.Descriptor instead.
func (*SndMsg) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{9}
}

func (x *SndMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *SndMsg) GetMsg() isSndMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *SndMsg) GetEvent() *SndEvent {
	if x, ok := x.GetMsg().(*SndMsg_Event); ok {
		return x.Event
	}
	return nil
}

func (x *SndMsg) GetError() *Error {
	if x, ok := x.GetMsg().(*SndMsg_Error); ok {
		return x.Error
	}
	return nil
}

func (x *SndMsg) GetSeqNo() int32 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

type isSndMsg_Msg interface {
	isSndMsg_Msg()
}

type SndMsg_Event struct {
	Event *SndEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type SndMsg_Error struct {
	Error *Error `protobuf:"bytes,9,opt,name=error,proto3,oneof"`
}

func (*SndMsg_Event) isSndMsg_Msg() {}

func (*SndMsg_Error) isSndMsg_Msg() {}

type FileEvent_Line struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line string `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
}

func (x *FileEvent_Line) Reset() {
	*x = FileEvent_Line{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileEvent_Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent_Line) ProtoMessage() {}

func (x *FileEvent_Line) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent_Line.ProtoReflect.Descriptor instead.
func (*FileEvent_Line) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{2, 0}
}

func (x *FileEvent_Line) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type JoyEvent_Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blink      bool   `protobuf:"varint,1,opt,name=blink,proto3" json:"blink,omitempty"`
	Brightness uint32 `protobuf:"varint,2,opt,name=brightness,proto3" json:"brightness,omitempty"`
	Color      uint32 `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	Shift      bool   `protobuf:"varint,4,opt,name=shift,proto3" json:"shift,omitempty"`
	Mode       uint32 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *JoyEvent_Device) Reset() {
	*x = JoyEvent_Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent_Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent_Device) ProtoMessage() {}

func (x *JoyEvent_Device) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent_Device.ProtoReflect.Descriptor instead.
func (*JoyEvent_Device) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{3, 0}
}

func (x *JoyEvent_Device) GetBlink() bool {
	if x != nil {
		return x.Blink
	}
	return false
}

func (x *JoyEvent_Device) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *JoyEvent_Device) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *JoyEvent_Device) GetShift() bool {
	if x != nil {
		return x.Shift
	}
	return false
}

func (x *JoyEvent_Device) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type JoyEvent_Button struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Color      string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Brightness uint32 `protobuf:"varint,3,opt,name=brightness,proto3" json:"brightness,omitempty"`
	Blink      bool   `protobuf:"varint,4,opt,name=blink,proto3" json:"blink,omitempty"`
	Pressed    bool   `protobuf:"varint,5,opt,name=pressed,proto3" json:"pressed,omitempty"`
}

func (x *JoyEvent_Button) Reset() {
	*x = JoyEvent_Button{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent_Button) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent_Button) ProtoMessage() {}

func (x *JoyEvent_Button) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent_Button.ProtoReflect.Descriptor instead.
func (*JoyEvent_Button) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{3, 1}
}

func (x *JoyEvent_Button) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoyEvent_Button) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *JoyEvent_Button) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *JoyEvent_Button) GetBlink() bool {
	if x != nil {
		return x.Blink
	}
	return false
}

func (x *JoyEvent_Button) GetPressed() bool {
	if x != nil {
		return x.Pressed
	}
	return false
}

type JoyEvent_Hud struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Direction string `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *JoyEvent_Hud) Reset() {
	*x = JoyEvent_Hud{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent_Hud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent_Hud) ProtoMessage() {}

func (x *JoyEvent_Hud) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent_Hud.ProtoReflect.Descriptor instead.
func (*JoyEvent_Hud) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{3, 2}
}

func (x *JoyEvent_Hud) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoyEvent_Hud) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type JoyEvent_MFD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Line       uint32 `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Brightness uint32 `protobuf:"varint,4,opt,name=brightness,proto3" json:"brightness,omitempty"`
}

func (x *JoyEvent_MFD) Reset() {
	*x = JoyEvent_MFD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent_MFD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent_MFD) ProtoMessage() {}

func (x *JoyEvent_MFD) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent_MFD.ProtoReflect.Descriptor instead.
func (*JoyEvent_MFD) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{3, 3}
}

func (x *JoyEvent_MFD) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoyEvent_MFD) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *JoyEvent_MFD) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *JoyEvent_MFD) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type JoyEvent_Led struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brightness uint32 `protobuf:"varint,2,opt,name=brightness,proto3" json:"brightness,omitempty"`
	Blink      bool   `protobuf:"varint,3,opt,name=blink,proto3" json:"blink,omitempty"`
}

func (x *JoyEvent_Led) Reset() {
	*x = JoyEvent_Led{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent_Led) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent_Led) ProtoMessage() {}

func (x *JoyEvent_Led) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent_Led.ProtoReflect.Descriptor instead.
func (*JoyEvent_Led) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{3, 4}
}

func (x *JoyEvent_Led) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoyEvent_Led) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *JoyEvent_Led) GetBlink() bool {
	if x != nil {
		return x.Blink
	}
	return false
}

type KbdEvent_Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pressed bool   `protobuf:"varint,2,opt,name=pressed,proto3" json:"pressed,omitempty"`
}

func (x *KbdEvent_Key) Reset() {
	*x = KbdEvent_Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KbdEvent_Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KbdEvent_Key) ProtoMessage() {}

func (x *KbdEvent_Key) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KbdEvent_Key.ProtoReflect.Descriptor instead.
func (*KbdEvent_Key) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{4, 0}
}

func (x *KbdEvent_Key) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KbdEvent_Key) GetPressed() bool {
	if x != nil {
		return x.Pressed
	}
	return false
}

type KbdEvent_Led struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	On bool   `protobuf:"varint,2,opt,name=on,proto3" json:"on,omitempty"`
}

func (x *KbdEvent_Led) Reset() {
	*x = KbdEvent_Led{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KbdEvent_Led) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KbdEvent_Led) ProtoMessage() {}

func (x *KbdEvent_Led) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KbdEvent_Led.ProtoReflect.Descriptor instead.
func (*KbdEvent_Led) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{4, 1}
}

func (x *KbdEvent_Led) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KbdEvent_Led) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

type SndEvent_Track struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Track  string `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	Volume uint32 `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Play   bool   `protobuf:"varint,3,opt,name=play,proto3" json:"play,omitempty"`
}

func (x *SndEvent_Track) Reset() {
	*x = SndEvent_Track{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SndEvent_Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SndEvent_Track) ProtoMessage() {}

func (x *SndEvent_Track) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SndEvent_Track.ProtoReflect.Descriptor instead.
func (*SndEvent_Track) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SndEvent_Track) GetTrack() string {
	if x != nil {
		return x.Track
	}
	return ""
}

func (x *SndEvent_Track) GetVolume() uint32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *SndEvent_Track) GetPlay() bool {
	if x != nil {
		return x.Play
	}
	return false
}

var File_pkg_gamenodepb_gamenodepb_proto protoreflect.FileDescriptor

var file_pkg_gamenodepb_gamenodepb_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x22, 0x36, 0x0a,
	0x07, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x22, 0x2b, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4a, 0x4f,
	0x59, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4b, 0x42, 0x44, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03,
	0x53, 0x4e, 0x44, 0x10, 0x03, 0x22, 0x2f, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x60, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x48, 0x00, 0x52,
	0x04, 0x6c, 0x69, 0x6e, 0x65, 0x1a, 0x1a, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e,
	0x65, 0x42, 0x05, 0x0a, 0x03, 0x4f, 0x62, 0x6a, 0x22, 0xea, 0x05, 0x0a, 0x08, 0x4a, 0x6f, 0x79,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x35, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x03,
	0x6d, 0x66, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x4d, 0x46, 0x44, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x66, 0x64, 0x12, 0x35, 0x0a, 0x06, 0x62, 0x75,
	0x74, 0x74, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f,
	0x6e, 0x12, 0x2c, 0x0a, 0x03, 0x68, 0x75, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x75, 0x64, 0x48, 0x00, 0x52, 0x03, 0x68, 0x75, 0x64, 0x12,
	0x2c, 0x0a, 0x03, 0x6c, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x4c, 0x65, 0x64, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x65, 0x64, 0x1a, 0x7e, 0x0a,
	0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x69, 0x6e, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1e, 0x0a,
	0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x69, 0x66, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x73, 0x68, 0x69, 0x66, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x1a, 0x7e, 0x0a,
	0x06, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1e, 0x0a,
	0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x62, 0x6c,
	0x69, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x1a, 0x33, 0x0a,
	0x03, 0x48, 0x75, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x5d, 0x0a, 0x03, 0x4d, 0x46, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73,
	0x73, 0x1a, 0x4b, 0x0a, 0x03, 0x4c, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x69, 0x6e,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x42, 0x05,
	0x0a, 0x03, 0x4f, 0x62, 0x6a, 0x22, 0xc5, 0x01, 0x0a, 0x08, 0x4b, 0x62, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4b, 0x62, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x2c, 0x0a, 0x03, 0x6c, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4b, 0x62, 0x64, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x65, 0x64, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x65, 0x64, 0x1a, 0x2f,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x1a,
	0x25, 0x0a, 0x03, 0x4c, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6e, 0x42, 0x05, 0x0a, 0x03, 0x4f, 0x62, 0x6a, 0x22, 0x90, 0x01,
	0x0a, 0x08, 0x53, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x05, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x1a, 0x49,
	0x0a, 0x05, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x42, 0x05, 0x0a, 0x03, 0x4f, 0x62, 0x6a,
	0x22, 0x94, 0x01, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2d, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x29, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65,
	0x71, 0x4e, 0x6f, 0x18, 0x63, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x65, 0x71, 0x4e, 0x6f,
	0x42, 0x05, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x92, 0x01, 0x0a, 0x06, 0x4a, 0x6f, 0x79, 0x4d,
	0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x65, 0x71, 0x4e, 0x6f, 0x18, 0x63, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x73, 0x65, 0x71, 0x4e, 0x6f, 0x42, 0x05, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x92, 0x01, 0x0a,
	0x06, 0x4b, 0x62, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4b, 0x62, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e,
	0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x71, 0x4e, 0x6f, 0x18, 0x63, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x65, 0x71, 0x4e, 0x6f, 0x42, 0x05, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x22, 0x92, 0x01, 0x0a, 0x06, 0x53, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2c, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x29,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x71,
	0x4e, 0x6f, 0x18, 0x63, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x65, 0x71, 0x4e, 0x6f, 0x42,
	0x05, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x32, 0xe1, 0x01, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x73, 0x67,
	0x1a, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x33, 0x0a, 0x03, 0x4a,
	0x6f, 0x79, 0x12, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e,
	0x4a, 0x6f, 0x79, 0x4d, 0x73, 0x67, 0x1a, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64,
	0x65, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x33, 0x0a, 0x03, 0x4b, 0x62, 0x64, 0x12, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f,
	0x64, 0x65, 0x70, 0x62, 0x2e, 0x4b, 0x62, 0x64, 0x4d, 0x73, 0x67, 0x1a, 0x12, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4b, 0x62, 0x64, 0x4d, 0x73, 0x67, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x33, 0x0a, 0x03, 0x53, 0x6e, 0x64, 0x12, 0x12, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x64, 0x4d, 0x73, 0x67,
	0x1a, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x6e,
	0x64, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x6e,
	0x6f, 0x64, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_gamenodepb_gamenodepb_proto_rawDescOnce sync.Once
	file_pkg_gamenodepb_gamenodepb_proto_rawDescData = file_pkg_gamenodepb_gamenodepb_proto_rawDesc
)

func file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP() []byte {
	file_pkg_gamenodepb_gamenodepb_proto_rawDescOnce.Do(func() {
		file_pkg_gamenodepb_gamenodepb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_gamenodepb_gamenodepb_proto_rawDescData)
	})
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescData
}

var file_pkg_gamenodepb_gamenodepb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_gamenodepb_gamenodepb_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pkg_gamenodepb_gamenodepb_proto_goTypes = []interface{}{
	(Backend_Type)(0),       // 0: gamenodepb.Backend.Type
	(*Backend)(nil),         // 1: gamenodepb.Backend
	(*Error)(nil),           // 2: gamenodepb.Error
	(*FileEvent)(nil),       // 3: gamenodepb.FileEvent
	(*JoyEvent)(nil),        // 4: gamenodepb.JoyEvent
	(*KbdEvent)(nil),        // 5: gamenodepb.KbdEvent
	(*SndEvent)(nil),        // 6: gamenodepb.SndEvent
	(*FileMsg)(nil),         // 7: gamenodepb.FileMsg
	(*JoyMsg)(nil),          // 8: gamenodepb.JoyMsg
	(*KbdMsg)(nil),          // 9: gamenodepb.KbdMsg
	(*SndMsg)(nil),          // 10: gamenodepb.SndMsg
	(*FileEvent_Line)(nil),  // 11: gamenodepb.FileEvent.Line
	(*JoyEvent_Device)(nil), // 12: gamenodepb.JoyEvent.Device
	(*JoyEvent_Button)(nil), // 13: gamenodepb.JoyEvent.Button
	(*JoyEvent_Hud)(nil),    // 14: gamenodepb.JoyEvent.Hud
	(*JoyEvent_MFD)(nil),    // 15: gamenodepb.JoyEvent.MFD
	(*JoyEvent_Led)(nil),    // 16: gamenodepb.JoyEvent.Led
	(*KbdEvent_Key)(nil),    // 17: gamenodepb.KbdEvent.Key
	(*KbdEvent_Led)(nil),    // 18: gamenodepb.KbdEvent.Led
	(*SndEvent_Track)(nil),  // 19: gamenodepb.SndEvent.Track
}
var file_pkg_gamenodepb_gamenodepb_proto_depIdxs = []int32{
	11, // 0: gamenodepb.FileEvent.line:type_name -> gamenodepb.FileEvent.Line
	12, // 1: gamenodepb.JoyEvent.device:type_name -> gamenodepb.JoyEvent.Device
	15, // 2: gamenodepb.JoyEvent.mfd:type_name -> gamenodepb.JoyEvent.MFD
	13, // 3: gamenodepb.JoyEvent.button:type_name -> gamenodepb.JoyEvent.Button
	14, // 4: gamenodepb.JoyEvent.hud:type_name -> gamenodepb.JoyEvent.Hud
	16, // 5: gamenodepb.JoyEvent.led:type_name -> gamenodepb.JoyEvent.Led
	17, // 6: gamenodepb.KbdEvent.key:type_name -> gamenodepb.KbdEvent.Key
	18, // 7: gamenodepb.KbdEvent.led:type_name -> gamenodepb.KbdEvent.Led
	19, // 8: gamenodepb.SndEvent.track:type_name -> gamenodepb.SndEvent.Track
	3,  // 9: gamenodepb.FileMsg.event:type_name -> gamenodepb.FileEvent
	2,  // 10: gamenodepb.FileMsg.error:type_name -> gamenodepb.Error
	4,  // 11: gamenodepb.JoyMsg.event:type_name -> gamenodepb.JoyEvent
	2,  // 12: gamenodepb.JoyMsg.error:type_name -> gamenodepb.Error
	5,  // 13: gamenodepb.KbdMsg.event:type_name -> gamenodepb.KbdEvent
	2,  // 14: gamenodepb.KbdMsg.error:type_name -> gamenodepb.Error
	6,  // 15: gamenodepb.SndMsg.event:type_name -> gamenodepb.SndEvent
	2,  // 16: gamenodepb.SndMsg.error:type_name -> gamenodepb.Error
	7,  // 17: gamenodepb.GameNode.File:input_type -> gamenodepb.FileMsg
	8,  // 18: gamenodepb.GameNode.Joy:input_type -> gamenodepb.JoyMsg
	9,  // 19: gamenodepb.GameNode.Kbd:input_type -> gamenodepb.KbdMsg
	10, // 20: gamenodepb.GameNode.Snd:input_type -> gamenodepb.SndMsg
	7,  // 21: gamenodepb.GameNode.File:output_type -> gamenodepb.FileMsg
	8,  // 22: gamenodepb.GameNode.Joy:output_type -> gamenodepb.JoyMsg
	9,  // 23: gamenodepb.GameNode.Kbd:output_type -> gamenodepb.KbdMsg
	10, // 24: gamenodepb.GameNode.Snd:output_type -> gamenodepb.SndMsg
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_pkg_gamenodepb_gamenodepb_proto_init() }
func file_pkg_gamenodepb_gamenodepb_proto_init() {
	if File_pkg_gamenodepb_gamenodepb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Backend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KbdEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SndEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KbdMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SndMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileEvent_Line); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent_Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent_Button); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent_Hud); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent_MFD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent_Led); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KbdEvent_Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KbdEvent_Led); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SndEvent_Track); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*FileEvent_Line_)(nil),
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*JoyEvent_Device_)(nil),
		(*JoyEvent_Mfd)(nil),
		(*JoyEvent_Button_)(nil),
		(*JoyEvent_Hud_)(nil),
		(*JoyEvent_Led_)(nil),
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*KbdEvent_Key_)(nil),
		(*KbdEvent_Led_)(nil),
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*SndEvent_Track_)(nil),
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*FileMsg_Event)(nil),
		(*FileMsg_Error)(nil),
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*JoyMsg_Event)(nil),
		(*JoyMsg_Error)(nil),
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*KbdMsg_Event)(nil),
		(*KbdMsg_Error)(nil),
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*SndMsg_Event)(nil),
		(*SndMsg_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_gamenodepb_gamenodepb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_gamenodepb_gamenodepb_proto_goTypes,
		DependencyIndexes: file_pkg_gamenodepb_gamenodepb_proto_depIdxs,
		EnumInfos:         file_pkg_gamenodepb_gamenodepb_proto_enumTypes,
		MessageInfos:      file_pkg_gamenodepb_gamenodepb_proto_msgTypes,
	}.Build()
	File_pkg_gamenodepb_gamenodepb_proto = out.File
	file_pkg_gamenodepb_gamenodepb_proto_rawDesc = nil
	file_pkg_gamenodepb_gamenodepb_proto_goTypes = nil
	file_pkg_gamenodepb_gamenodepb_proto_depIdxs = nil
}
