// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: pkg/gamenodepb/gamenodepb.proto

package gamenodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FileEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Event:
	//	*FileEvent_Line_
	//	*FileEvent_Error
	Event isFileEvent_Event `protobuf_oneof:"Event"`
}

func (x *FileEvent) Reset() {
	*x = FileEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent) ProtoMessage() {}

func (x *FileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent.ProtoReflect.Descriptor instead.
func (*FileEvent) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{1}
}

func (x *FileEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *FileEvent) GetEvent() isFileEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *FileEvent) GetLine() *FileEvent_Line {
	if x, ok := x.GetEvent().(*FileEvent_Line_); ok {
		return x.Line
	}
	return nil
}

func (x *FileEvent) GetError() *Error {
	if x, ok := x.GetEvent().(*FileEvent_Error); ok {
		return x.Error
	}
	return nil
}

type isFileEvent_Event interface {
	isFileEvent_Event()
}

type FileEvent_Line_ struct {
	Line *FileEvent_Line `protobuf:"bytes,10,opt,name=line,proto3,oneof"`
}

type FileEvent_Error struct {
	Error *Error `protobuf:"bytes,99,opt,name=error,proto3,oneof"`
}

func (*FileEvent_Line_) isFileEvent_Event() {}

func (*FileEvent_Error) isFileEvent_Event() {}

type JoyEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Event:
	//	*JoyEvent_Device_
	//	*JoyEvent_Mfd
	//	*JoyEvent_Button_
	//	*JoyEvent_Hud_
	//	*JoyEvent_Led_
	//	*JoyEvent_Error
	Event isJoyEvent_Event `protobuf_oneof:"Event"`
}

func (x *JoyEvent) Reset() {
	*x = JoyEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent) ProtoMessage() {}

func (x *JoyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent.ProtoReflect.Descriptor instead.
func (*JoyEvent) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{2}
}

func (x *JoyEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *JoyEvent) GetEvent() isJoyEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *JoyEvent) GetDevice() *JoyEvent_Device {
	if x, ok := x.GetEvent().(*JoyEvent_Device_); ok {
		return x.Device
	}
	return nil
}

func (x *JoyEvent) GetMfd() *JoyEvent_MFD {
	if x, ok := x.GetEvent().(*JoyEvent_Mfd); ok {
		return x.Mfd
	}
	return nil
}

func (x *JoyEvent) GetButton() *JoyEvent_Button {
	if x, ok := x.GetEvent().(*JoyEvent_Button_); ok {
		return x.Button
	}
	return nil
}

func (x *JoyEvent) GetHud() *JoyEvent_Hud {
	if x, ok := x.GetEvent().(*JoyEvent_Hud_); ok {
		return x.Hud
	}
	return nil
}

func (x *JoyEvent) GetLed() *JoyEvent_Led {
	if x, ok := x.GetEvent().(*JoyEvent_Led_); ok {
		return x.Led
	}
	return nil
}

func (x *JoyEvent) GetError() *Error {
	if x, ok := x.GetEvent().(*JoyEvent_Error); ok {
		return x.Error
	}
	return nil
}

type isJoyEvent_Event interface {
	isJoyEvent_Event()
}

type JoyEvent_Device_ struct {
	Device *JoyEvent_Device `protobuf:"bytes,10,opt,name=device,proto3,oneof"`
}

type JoyEvent_Mfd struct {
	Mfd *JoyEvent_MFD `protobuf:"bytes,11,opt,name=mfd,proto3,oneof"`
}

type JoyEvent_Button_ struct {
	Button *JoyEvent_Button `protobuf:"bytes,12,opt,name=button,proto3,oneof"`
}

type JoyEvent_Hud_ struct {
	Hud *JoyEvent_Hud `protobuf:"bytes,13,opt,name=hud,proto3,oneof"`
}

type JoyEvent_Led_ struct {
	Led *JoyEvent_Led `protobuf:"bytes,14,opt,name=led,proto3,oneof"`
}

type JoyEvent_Error struct {
	Error *Error `protobuf:"bytes,99,opt,name=error,proto3,oneof"`
}

func (*JoyEvent_Device_) isJoyEvent_Event() {}

func (*JoyEvent_Mfd) isJoyEvent_Event() {}

func (*JoyEvent_Button_) isJoyEvent_Event() {}

func (*JoyEvent_Hud_) isJoyEvent_Event() {}

func (*JoyEvent_Led_) isJoyEvent_Event() {}

func (*JoyEvent_Error) isJoyEvent_Event() {}

type KbdEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Event:
	//	*KbdEvent_Key_
	//	*KbdEvent_Led_
	//	*KbdEvent_Error
	Event isKbdEvent_Event `protobuf_oneof:"Event"`
}

func (x *KbdEvent) Reset() {
	*x = KbdEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KbdEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KbdEvent) ProtoMessage() {}

func (x *KbdEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KbdEvent.ProtoReflect.Descriptor instead.
func (*KbdEvent) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{3}
}

func (x *KbdEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *KbdEvent) GetEvent() isKbdEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *KbdEvent) GetKey() *KbdEvent_Key {
	if x, ok := x.GetEvent().(*KbdEvent_Key_); ok {
		return x.Key
	}
	return nil
}

func (x *KbdEvent) GetLed() *KbdEvent_Led {
	if x, ok := x.GetEvent().(*KbdEvent_Led_); ok {
		return x.Led
	}
	return nil
}

func (x *KbdEvent) GetError() *Error {
	if x, ok := x.GetEvent().(*KbdEvent_Error); ok {
		return x.Error
	}
	return nil
}

type isKbdEvent_Event interface {
	isKbdEvent_Event()
}

type KbdEvent_Key_ struct {
	Key *KbdEvent_Key `protobuf:"bytes,10,opt,name=key,proto3,oneof"`
}

type KbdEvent_Led_ struct {
	Led *KbdEvent_Led `protobuf:"bytes,11,opt,name=led,proto3,oneof"`
}

type KbdEvent_Error struct {
	Error *Error `protobuf:"bytes,99,opt,name=error,proto3,oneof"`
}

func (*KbdEvent_Key_) isKbdEvent_Event() {}

func (*KbdEvent_Led_) isKbdEvent_Event() {}

func (*KbdEvent_Error) isKbdEvent_Event() {}

type SndEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Event:
	//	*SndEvent_Track_
	//	*SndEvent_Error
	Event isSndEvent_Event `protobuf_oneof:"Event"`
}

func (x *SndEvent) Reset() {
	*x = SndEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SndEvent) ProtoMessage() {}

func (x *SndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SndEvent.ProtoReflect.Descriptor instead.
func (*SndEvent) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{4}
}

func (x *SndEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *SndEvent) GetEvent() isSndEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *SndEvent) GetTrack() *SndEvent_Track {
	if x, ok := x.GetEvent().(*SndEvent_Track_); ok {
		return x.Track
	}
	return nil
}

func (x *SndEvent) GetError() *Error {
	if x, ok := x.GetEvent().(*SndEvent_Error); ok {
		return x.Error
	}
	return nil
}

type isSndEvent_Event interface {
	isSndEvent_Event()
}

type SndEvent_Track_ struct {
	Track *SndEvent_Track `protobuf:"bytes,10,opt,name=track,proto3,oneof"`
}

type SndEvent_Error struct {
	Error *Error `protobuf:"bytes,99,opt,name=error,proto3,oneof"`
}

func (*SndEvent_Track_) isSndEvent_Event() {}

func (*SndEvent_Error) isSndEvent_Event() {}

type FileEvent_Line struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line string `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
}

func (x *FileEvent_Line) Reset() {
	*x = FileEvent_Line{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileEvent_Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent_Line) ProtoMessage() {}

func (x *FileEvent_Line) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent_Line.ProtoReflect.Descriptor instead.
func (*FileEvent_Line) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FileEvent_Line) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type JoyEvent_Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blink      bool   `protobuf:"varint,1,opt,name=blink,proto3" json:"blink,omitempty"`
	Brightness uint32 `protobuf:"varint,2,opt,name=brightness,proto3" json:"brightness,omitempty"`
	Color      uint32 `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	Shift      bool   `protobuf:"varint,4,opt,name=shift,proto3" json:"shift,omitempty"`
	Mode       uint32 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *JoyEvent_Device) Reset() {
	*x = JoyEvent_Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent_Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent_Device) ProtoMessage() {}

func (x *JoyEvent_Device) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent_Device.ProtoReflect.Descriptor instead.
func (*JoyEvent_Device) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{2, 0}
}

func (x *JoyEvent_Device) GetBlink() bool {
	if x != nil {
		return x.Blink
	}
	return false
}

func (x *JoyEvent_Device) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *JoyEvent_Device) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *JoyEvent_Device) GetShift() bool {
	if x != nil {
		return x.Shift
	}
	return false
}

func (x *JoyEvent_Device) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type JoyEvent_Button struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Color      string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Brightness uint32 `protobuf:"varint,3,opt,name=brightness,proto3" json:"brightness,omitempty"`
	Blink      bool   `protobuf:"varint,4,opt,name=blink,proto3" json:"blink,omitempty"`
	Pressed    bool   `protobuf:"varint,5,opt,name=pressed,proto3" json:"pressed,omitempty"`
}

func (x *JoyEvent_Button) Reset() {
	*x = JoyEvent_Button{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent_Button) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent_Button) ProtoMessage() {}

func (x *JoyEvent_Button) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent_Button.ProtoReflect.Descriptor instead.
func (*JoyEvent_Button) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{2, 1}
}

func (x *JoyEvent_Button) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoyEvent_Button) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *JoyEvent_Button) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *JoyEvent_Button) GetBlink() bool {
	if x != nil {
		return x.Blink
	}
	return false
}

func (x *JoyEvent_Button) GetPressed() bool {
	if x != nil {
		return x.Pressed
	}
	return false
}

type JoyEvent_Hud struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Direction string `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *JoyEvent_Hud) Reset() {
	*x = JoyEvent_Hud{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent_Hud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent_Hud) ProtoMessage() {}

func (x *JoyEvent_Hud) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent_Hud.ProtoReflect.Descriptor instead.
func (*JoyEvent_Hud) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{2, 2}
}

func (x *JoyEvent_Hud) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoyEvent_Hud) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type JoyEvent_MFD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Line       uint32 `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Brightness uint32 `protobuf:"varint,4,opt,name=brightness,proto3" json:"brightness,omitempty"`
}

func (x *JoyEvent_MFD) Reset() {
	*x = JoyEvent_MFD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent_MFD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent_MFD) ProtoMessage() {}

func (x *JoyEvent_MFD) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent_MFD.ProtoReflect.Descriptor instead.
func (*JoyEvent_MFD) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{2, 3}
}

func (x *JoyEvent_MFD) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoyEvent_MFD) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *JoyEvent_MFD) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *JoyEvent_MFD) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type JoyEvent_Led struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brightness uint32 `protobuf:"varint,2,opt,name=brightness,proto3" json:"brightness,omitempty"`
	Blink      bool   `protobuf:"varint,3,opt,name=blink,proto3" json:"blink,omitempty"`
}

func (x *JoyEvent_Led) Reset() {
	*x = JoyEvent_Led{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyEvent_Led) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyEvent_Led) ProtoMessage() {}

func (x *JoyEvent_Led) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyEvent_Led.ProtoReflect.Descriptor instead.
func (*JoyEvent_Led) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{2, 4}
}

func (x *JoyEvent_Led) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoyEvent_Led) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *JoyEvent_Led) GetBlink() bool {
	if x != nil {
		return x.Blink
	}
	return false
}

type KbdEvent_Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pressed bool   `protobuf:"varint,2,opt,name=pressed,proto3" json:"pressed,omitempty"`
}

func (x *KbdEvent_Key) Reset() {
	*x = KbdEvent_Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KbdEvent_Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KbdEvent_Key) ProtoMessage() {}

func (x *KbdEvent_Key) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KbdEvent_Key.ProtoReflect.Descriptor instead.
func (*KbdEvent_Key) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{3, 0}
}

func (x *KbdEvent_Key) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KbdEvent_Key) GetPressed() bool {
	if x != nil {
		return x.Pressed
	}
	return false
}

type KbdEvent_Led struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	On bool   `protobuf:"varint,2,opt,name=on,proto3" json:"on,omitempty"`
}

func (x *KbdEvent_Led) Reset() {
	*x = KbdEvent_Led{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KbdEvent_Led) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KbdEvent_Led) ProtoMessage() {}

func (x *KbdEvent_Led) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KbdEvent_Led.ProtoReflect.Descriptor instead.
func (*KbdEvent_Led) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{3, 1}
}

func (x *KbdEvent_Led) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KbdEvent_Led) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

type SndEvent_Track struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Volume uint32 `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Play   bool   `protobuf:"varint,3,opt,name=play,proto3" json:"play,omitempty"`
}

func (x *SndEvent_Track) Reset() {
	*x = SndEvent_Track{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SndEvent_Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SndEvent_Track) ProtoMessage() {}

func (x *SndEvent_Track) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gamenodepb_gamenodepb_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SndEvent_Track.ProtoReflect.Descriptor instead.
func (*SndEvent_Track) Descriptor() ([]byte, []int) {
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SndEvent_Track) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SndEvent_Track) GetVolume() uint32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *SndEvent_Track) GetPlay() bool {
	if x != nil {
		return x.Play
	}
	return false
}

var File_pkg_gamenodepb_gamenodepb_proto protoreflect.FileDescriptor

var file_pkg_gamenodepb_gamenodepb_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x22, 0x2d, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xa1, 0x01, 0x0a,
	0x09, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x29, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x63, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x1a, 0x0a, 0x04, 0x4c,
	0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0xab, 0x06, 0x0a, 0x08, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x35, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4a,
	0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x48, 0x00,
	0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x6d, 0x66, 0x64, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x46, 0x44, 0x48,
	0x00, 0x52, 0x03, 0x6d, 0x66, 0x64, 0x12, 0x35, 0x0a, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64,
	0x65, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x42, 0x75, 0x74,
	0x74, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x2c, 0x0a,
	0x03, 0x68, 0x75, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x48, 0x75, 0x64, 0x48, 0x00, 0x52, 0x03, 0x68, 0x75, 0x64, 0x12, 0x2c, 0x0a, 0x03, 0x6c,
	0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e,
	0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4c,
	0x65, 0x64, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x63, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e,
	0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x1a, 0x7e, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x62,
	0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x6e, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68,
	0x69, 0x66, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x68, 0x69, 0x66, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x1a, 0x7e, 0x0a, 0x06, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x6e, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x65, 0x64, 0x1a, 0x33, 0x0a, 0x03, 0x48, 0x75, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x5d, 0x0a, 0x03, 0x4d, 0x46, 0x44,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x1a, 0x4b, 0x0a, 0x03, 0x4c, 0x65, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x42, 0x07, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x86,
	0x02, 0x0a, 0x08, 0x4b, 0x62, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x2c, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4b, 0x62, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a,
	0x03, 0x6c, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4b, 0x62, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x4c, 0x65, 0x64, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x63, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x2f, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x1a, 0x25, 0x0a, 0x03, 0x4c, 0x65, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6e, 0x42, 0x07,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xcb, 0x01, 0x0a, 0x08, 0x53, 0x6e, 0x64, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f,
	0x64, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x29, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x63, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x43, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x42, 0x07, 0x0a, 0x05,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x32, 0xf1, 0x01, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x1a, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x37,
	0x0a, 0x03, 0x4a, 0x6f, 0x79, 0x12, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x79, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x37, 0x0a, 0x03, 0x4b, 0x62, 0x64, 0x12, 0x14,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x4b, 0x62, 0x64, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70,
	0x62, 0x2e, 0x4b, 0x62, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x37, 0x0a, 0x03, 0x53, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f,
	0x64, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x14, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x64, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x6f,
	0x64, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_gamenodepb_gamenodepb_proto_rawDescOnce sync.Once
	file_pkg_gamenodepb_gamenodepb_proto_rawDescData = file_pkg_gamenodepb_gamenodepb_proto_rawDesc
)

func file_pkg_gamenodepb_gamenodepb_proto_rawDescGZIP() []byte {
	file_pkg_gamenodepb_gamenodepb_proto_rawDescOnce.Do(func() {
		file_pkg_gamenodepb_gamenodepb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_gamenodepb_gamenodepb_proto_rawDescData)
	})
	return file_pkg_gamenodepb_gamenodepb_proto_rawDescData
}

var file_pkg_gamenodepb_gamenodepb_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_gamenodepb_gamenodepb_proto_goTypes = []interface{}{
	(*Error)(nil),           // 0: gamenodepb.Error
	(*FileEvent)(nil),       // 1: gamenodepb.FileEvent
	(*JoyEvent)(nil),        // 2: gamenodepb.JoyEvent
	(*KbdEvent)(nil),        // 3: gamenodepb.KbdEvent
	(*SndEvent)(nil),        // 4: gamenodepb.SndEvent
	(*FileEvent_Line)(nil),  // 5: gamenodepb.FileEvent.Line
	(*JoyEvent_Device)(nil), // 6: gamenodepb.JoyEvent.Device
	(*JoyEvent_Button)(nil), // 7: gamenodepb.JoyEvent.Button
	(*JoyEvent_Hud)(nil),    // 8: gamenodepb.JoyEvent.Hud
	(*JoyEvent_MFD)(nil),    // 9: gamenodepb.JoyEvent.MFD
	(*JoyEvent_Led)(nil),    // 10: gamenodepb.JoyEvent.Led
	(*KbdEvent_Key)(nil),    // 11: gamenodepb.KbdEvent.Key
	(*KbdEvent_Led)(nil),    // 12: gamenodepb.KbdEvent.Led
	(*SndEvent_Track)(nil),  // 13: gamenodepb.SndEvent.Track
}
var file_pkg_gamenodepb_gamenodepb_proto_depIdxs = []int32{
	5,  // 0: gamenodepb.FileEvent.line:type_name -> gamenodepb.FileEvent.Line
	0,  // 1: gamenodepb.FileEvent.error:type_name -> gamenodepb.Error
	6,  // 2: gamenodepb.JoyEvent.device:type_name -> gamenodepb.JoyEvent.Device
	9,  // 3: gamenodepb.JoyEvent.mfd:type_name -> gamenodepb.JoyEvent.MFD
	7,  // 4: gamenodepb.JoyEvent.button:type_name -> gamenodepb.JoyEvent.Button
	8,  // 5: gamenodepb.JoyEvent.hud:type_name -> gamenodepb.JoyEvent.Hud
	10, // 6: gamenodepb.JoyEvent.led:type_name -> gamenodepb.JoyEvent.Led
	0,  // 7: gamenodepb.JoyEvent.error:type_name -> gamenodepb.Error
	11, // 8: gamenodepb.KbdEvent.key:type_name -> gamenodepb.KbdEvent.Key
	12, // 9: gamenodepb.KbdEvent.led:type_name -> gamenodepb.KbdEvent.Led
	0,  // 10: gamenodepb.KbdEvent.error:type_name -> gamenodepb.Error
	13, // 11: gamenodepb.SndEvent.track:type_name -> gamenodepb.SndEvent.Track
	0,  // 12: gamenodepb.SndEvent.error:type_name -> gamenodepb.Error
	1,  // 13: gamenodepb.GameNode.File:input_type -> gamenodepb.FileEvent
	2,  // 14: gamenodepb.GameNode.Joy:input_type -> gamenodepb.JoyEvent
	3,  // 15: gamenodepb.GameNode.Kbd:input_type -> gamenodepb.KbdEvent
	4,  // 16: gamenodepb.GameNode.Snd:input_type -> gamenodepb.SndEvent
	1,  // 17: gamenodepb.GameNode.File:output_type -> gamenodepb.FileEvent
	2,  // 18: gamenodepb.GameNode.Joy:output_type -> gamenodepb.JoyEvent
	3,  // 19: gamenodepb.GameNode.Kbd:output_type -> gamenodepb.KbdEvent
	4,  // 20: gamenodepb.GameNode.Snd:output_type -> gamenodepb.SndEvent
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_gamenodepb_gamenodepb_proto_init() }
func file_pkg_gamenodepb_gamenodepb_proto_init() {
	if File_pkg_gamenodepb_gamenodepb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KbdEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SndEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileEvent_Line); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent_Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent_Button); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent_Hud); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent_MFD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoyEvent_Led); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KbdEvent_Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KbdEvent_Led); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gamenodepb_gamenodepb_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SndEvent_Track); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*FileEvent_Line_)(nil),
		(*FileEvent_Error)(nil),
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*JoyEvent_Device_)(nil),
		(*JoyEvent_Mfd)(nil),
		(*JoyEvent_Button_)(nil),
		(*JoyEvent_Hud_)(nil),
		(*JoyEvent_Led_)(nil),
		(*JoyEvent_Error)(nil),
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*KbdEvent_Key_)(nil),
		(*KbdEvent_Led_)(nil),
		(*KbdEvent_Error)(nil),
	}
	file_pkg_gamenodepb_gamenodepb_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*SndEvent_Track_)(nil),
		(*SndEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_gamenodepb_gamenodepb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_gamenodepb_gamenodepb_proto_goTypes,
		DependencyIndexes: file_pkg_gamenodepb_gamenodepb_proto_depIdxs,
		MessageInfos:      file_pkg_gamenodepb_gamenodepb_proto_msgTypes,
	}.Build()
	File_pkg_gamenodepb_gamenodepb_proto = out.File
	file_pkg_gamenodepb_gamenodepb_proto_rawDesc = nil
	file_pkg_gamenodepb_gamenodepb_proto_goTypes = nil
	file_pkg_gamenodepb_gamenodepb_proto_depIdxs = nil
}
